### ISSUE TITLE
minify concatenates lines in text content with no white space between them

### ISSUE THREAD

**Issue by noxpo** [derbyjs/html-util#2]
EOL and leading spaces in multi-line text blocks are just dropped instead of being converted to a single space char as they should in parsed HTML.

**Comment by enjalot** [comment]
this is intentional. html-util is not trying to match the browser's behavior, it is intended to be used with well understood html (derby templates).

this isn't really intended to be an html minifier for general html.

**Comment by noxpo** [comment]
I noticed this behavior when a derby template containing a paragraph of text was rendered by the browser in a strange way: every last word of a line of text in the template source was directly concatenated to the first word of the following line. Does this mean that derby templates are not supposed to contain more text than what would fit on one line in the browser?
